### ISSUE TITLE
Issue installing package on MacOS

### ISSUE THREAD

**Issue by jrdn91** [sandeepmistry/node-ancs#11]
I'm on MacOS Sierra `V. 10.12.1` trying to install the latest of this package which at this time is `0.1.2` and I just updated node to try to fix errors to `v7.2.1`

When attempting to run the `npm install ...` command I am getting errors

```
npm install ancs --save

> xpc-connection@0.1.4 install /Users/jordanriser/workspace/ancs-test/node_modules/xpc-connection
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/binding/src/XpcConnection.o
../src/XpcConnection.cpp:143:44: warning: 'GetRealNamedProperty' is deprecated
      [-Wdeprecated-declarations]
      Local<Value> propertyValue = object->GetRealNamedProperty(property...
                                           ^
/Users/jordanriser/.node-gyp/7.2.1/include/node/v8.h:2949:30: note: 
      'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
1 warning generated.
  SOLINK_MODULE(target) Release/binding.node

> noble@0.3.14 install /Users/jordanriser/workspace/ancs-test/node_modules/noble
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  LINK(target) Release/hci-ble
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.6.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/hci-ble] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jordanriser/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/jordanriser/.nvm/versions/node/v7.2.1/bin/node" "/Users/jordanriser/.nvm/versions/node/v7.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jordanriser/workspace/ancs-test/node_modules/noble
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN ancs-test@1.0.0 No repository field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/jordanriser/.nvm/versions/node/v7.2.1/bin/node" "/Users/jordanriser/.nvm/versions/node/v7.2.1/bin/npm" "install" "ancs" "--save"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! noble@0.3.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the noble@0.3.14 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the noble package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs noble
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls noble
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jordanriser/workspace/ancs-test/npm-debug.log
```

**Comment by sandeepmistry** [comment]
@Jordan4jc my guess is noble doesn't support Node.js v7 as of now ...

**Comment by jrdn91** [comment]
What version of node should I be using? I have NVM so I can use a specific version of node for just this project. I see noble is a very old version? Can this be updated without breaking any functionality so that it can be used with a newer version of node?

**Comment by sandeepmistry** [comment]
@Jordan4jc 

> What version of node should I be using?

Node.js 6.x works for me.

>  I see noble is a very old version?

You can try to update to the latest version of noble and submit a pull request if all is good.

**Comment by mhkeller** [comment]
Are there any plans to update this lib to work with more recent versions of Node? Version 6 is a bit out of date.

**Comment by mak3rm1k3** [comment]
Anyone have insights if this code be executed with a python server on a pi? I don't have any experience in JS.
