### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by fishsticks** [sandeepmistry/node-ancs#6]
I ran the script with DEBUG=mavericks-bindings . Getting the following error:

DEBUG=mavericks-bindings node notification.js 
discovered
connected
/Users/xxx/node_modules/ancs/node_modules/noble/lib/mac/yosemite.js:408
var serviceUuid = this._peripherals[deviceUuid].services[serviceStartHandle]
^
TypeError: Cannot read property '15' of undefined
at null. (/Users/xxx/node_modules/ancs/node_modules/noble/lib/mac/yosemite.js:408:59)
at emit (events.js:107:17)
at null. (/Users/xxx/node_modules/ancs/node_modules/noble/lib/mac/yosemite.js:33:8)
at emit (events.js:107:17)
at null. (/Users/xxx/node_modules/ancs/node_modules/noble/lib/mac/yosemite.js:15:59)
at XpcConnection.emit (events.js:107:17)

**Comment by sandeepmistry** [comment]
@fishsticks ```DEBUG=yosemite-bindings``` would provide better output, as it looks like you are running Yosemite and not Mavericks.

I believe https://github.com/sandeepmistry/noble/commit/d54bc83c6267ec6118fbfa2681aff3fc0cc5b016 from noble should fix this, it's hasn't been published to npm yet.
